name: Bug Report
description: File a bug report.
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Check out our [contributor guide](https://github.com/JqckB/gophercloud/blob/main/docs/contributor-tutorial/step-02-issues.md) to create effective issues.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: What happened, and what did you expect to happen?
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our Gophercloud are you running?
      options:
        - v2 (current)
        - v1 (legacy)
        - main (development)
      default: 0
    validations:
      required: true
